# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1 (8431e1c8-d61d-43da-80f2-e02677f52b6c)'
    mavenPomFile: 'pom.xml'
    options: '-B'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.21
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false

- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1 (8431e1c8-d61d-43da-80f2-e02677f52b6c)'
    mavenPomFile: 'pom.xml'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 1.21
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultWorkingDirectory)/target'
    Contents: '*.jar'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# - task: Docker@2
#   inputs:
#     command: 'build'
#     Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'acr.connection'
    repository: 'samples'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'java-app'

